Import libraries

In [2]:
import numpy as np
from time import process_time

Increase the efficiency

In [4]:
l1 = [i for i in range(100000000)]

start_time = process_time()

l1 = [i+5 for i in l1]

end_time = process_time()

print(end_time - start_time )


6.359375


In [22]:
arr = np.array([i for i in range(100000000)])

start_time = process_time()

arr = [i+5 for i in arr]

end_time = process_time()

print(end_time - start_time)

4.796875


Mathematical Operations

In this below example I want to add the elemnts in the list one to the elements of the list two, But list will get concatenated

In [23]:
l1 = [1,2,3]
l2 = [4,5,6]

print(l1+l2)

[1, 2, 3, 4, 5, 6]


But where as the array will get add the elements for arr1 to arr2

In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Operations on NumPy array

The datatype of the array is ndarray

In [26]:
# Creating the 1-d Array

arr = np.array([1,2,4])
print(arr)
arr.shape


[1 2 4]


(3,)

In [28]:
# Creating the 2-D array
arr = np.array([(1,2,3),(4,5,5)])
print(arr)
arr.shape

[[1 2 3]
 [4 5 5]]


(2, 3)

In [30]:
# convert the data type 
arr = np.array([(1,2,3),(4,5,5)], dtype=float)
print(arr)
arr.shape

[[1. 2. 3.]
 [4. 5. 5.]]


(2, 3)

In [32]:
#inplace zero
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [33]:
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
arr = np.full((2,3),5)
print(arr)

[[5 5 5]
 [5 5 5]]


In [35]:
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#Creating arrays filled with random values in NumPy

arr = np.random.random((2,3))       # It will generate the values form 0 - 1 
print(arr)

[[0.14375015 0.50819226 0.86681447]
 [0.02029305 0.71874484 0.94314766]]


In [ ]:
# if we specify the range, The numbers will be generated in that specifyed range 

arr = np.random.randint(1,100,(2,3))
print(arr)

[[36 95 22]
 [78 63 78]]


Convert the list to a array

In [41]:
l = [1,2,3]
arr = np.asarray(l)
print(arr)

[1 2 3]


Analysing the numpy array

In [42]:
c = np.random.randint(1,100,(5,5))
print(c)

[[89 26 91 24 22]
 [54 64 64 50 81]
 [23 86 76 27 43]
 [ 2 59 93 34 71]
 [38 21 33  8 32]]


In [43]:
print(c.shape)

(5, 5)


In [44]:
print(c.ndim)

2


In [45]:
print(c.size)

25


Array Manipulation

In [ ]:
arr = np.random.randint(1,100,(2,3))
print(arr)
# Transpose
arr = arr.T    # To convert the all the rows into columns and to conver the all the columns into rows
print(arr)

[[ 2 68 17]
 [80 49 42]]
[[ 2 80]
 [68 49]
 [17 42]]


In [49]:
arr = np.random.randint(1,100,(2,3))
print(arr)

arr = arr.reshape(3,2)
print(arr)


[[10 93 33]
 [36  7 60]]
[[10 93]
 [33 36]
 [ 7 60]]
